query gameSessionByPk($id: Int!) {
  game_session_by_pk(id: $id) {
    id
    host {
      id
      name
    }
    completion_status
    players(order_by: {created_at: asc}) {
      user {
        id
        name
      }
      game_session_id
      user_id
    }
    turn_index
    winner {
      id
      name
    }
    closest_guesser {
      id
      name
    }
    closest_guess
  }
}
